import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const chirp = localFont({
  src: [
    {
      path: "./fonts/Chirp-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Chirp-Medium.woff2",
      weight: "500",
      style: "normal",
    },

    {
      path: "./fonts/Chirp-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Chirp-Heavy.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-chirp",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${chirp.variable} font-sans bg-gray-100 text-gray-900 min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
